-- ============================================================
-- 把既有 POI 資料庫裡的機場資料重新分類成獨立的 'airport' category
-- 請在 useful_travel_schema.sql (基礎表) 之後執行即可; 但務必在 migration_poi_category_normalize.sql
-- 「之前」執行 (那份會把剩下的 category='交通' 轉成 'transport', 如果順序顛倒, 機場會先被那份
-- migration 誤轉成 'transport', 之後這份就再也篩不出機場了)。
--
-- 背景:
--   檢查過目前 POI 資料庫的實際資料後發現, 機場資料本來就已經存在 (約 150 筆),
--   original_name 也已經存了機場代碼 (例: TPE、NRT、ICN), 跟這次「機場當成 POI 資料庫
--   新分類」的設計完全吻合 —— 只是目前這些機場資料的 category 是 '交通', 跟火車站等其他
--   交通工具混在同一個分類裡, 沒有自己獨立的分類值, 導致「機場輸入框自動完成」如果用
--   category='airport' 去篩選會完全篩不到任何資料。
--
--   這份 migration 不是新增資料 (機場資料本來就有了, 不需要也不應該重複造一批新的),
--   而是把既有這 150 筆機場資料的 category 從 '交通' 改成 'airport', 讓它們可以被
--   /poi/autocomplete?category=airport 精準篩選出來、不會混到火車站。
--
--   判斷依據: category='交通' 且名稱包含「機場」兩個字的資料列全部都是機場 (已逐筆核對過
--   目前資料庫內容, 沒有例外, 也沒有其他分類下叫「XX機場」但其實不是機場的誤判)。
--   其餘屬於火車站等其他交通工具的資料列, category 維持 '交通' 不變, 不受影響。
--
-- 檢查資料時另外發現 POI 資料庫裡「景點/餐廳/飯店/購物」這幾類舊資料的 category 也是存中文,
-- 跟畫面篩選/表單送出的英文值對不上, 同樣的問題; 那部分改在下一份 migration_poi_category_normalize.sql
-- 處理 (依賴這份先把機場挑出來, 所以要接在這份後面執行)。
-- ============================================================

UPDATE poi SET category = 'airport' WHERE category = '交通' AND name LIKE '%機場%';
